services:
  backend:
    image: alterem/gemini-poise
    ports:
      - "8100:8000"
    volumes:
      - ./.env:/app/.env
      - ./data/:/data
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - redis
      - postgres
    restart: always

  frontend:
    image: alterem/gemini-poise-frontend
    ports:
      - "8101:80"
    environment:
      - TZ=Asia/Shanghai
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gemini_poise
      - TZ=Asia/Shanghai
    ports:
      - "5432:5432"
    restart: always

volumes:
  redis_data:
  postgres_data:
