services:
  backend:
    image: alterem/gemini-poise
    ports:
      - "8100:8000"
    volumes:
      - ./.env:/app/.env
      - ./data/:/data
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

  frontend:
    image: alterem/gemini-poise-frontend
    ports:
      - "8101:80"
    environment:
      - TZ=Asia/Shanghai
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.05'

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.05'
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru

  postgres:
    image: postgres:15
    profiles:
      - postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gemini_poise
      - TZ=Asia/Shanghai
    ports:
      - "5432:5432"
    restart: always

  mysql:
    image: mysql:8.0
    profiles:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-mysql}
      - MYSQL_DATABASE=gemini_poise
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    restart: always

volumes:
  redis_data:
  postgres_data:
  mysql_data:
