"""Add KeySurvivalStatistics table

Revision ID: 09d1f06cdc66
Revises: e7e214f5785e
Create Date: 2025-08-01 20:27:44.186558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d1f06cdc66'
down_revision: Union[str, None] = 'e7e214f5785e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_survival_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active_keys', sa.Integer(), nullable=False),
    sa.Column('exhausted_keys', sa.Integer(), nullable=False),
    sa.Column('error_keys', sa.Integer(), nullable=False),
    sa.Column('total_keys', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_survival_statistics_id'), 'key_survival_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_key_survival_statistics_timestamp'), 'key_survival_statistics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_survival_statistics_timestamp'), table_name='key_survival_statistics')
    op.drop_index(op.f('ix_key_survival_statistics_id'), table_name='key_survival_statistics')
    op.drop_table('key_survival_statistics')
    # ### end Alembic commands ###
