"""Add api_call_logs table

Revision ID: 47c2f4eaa5ea
Revises: 6b16d5da7d2b
Create Date: 2025-06-03 18:03:24.711113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c2f4eaa5ea'
down_revision: Union[str, None] = '6b16d5da7d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_logs_id'), 'api_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_call_logs_timestamp'), 'api_call_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_call_logs_timestamp'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_id'), table_name='api_call_logs')
    op.drop_table('api_call_logs')
    # ### end Alembic commands ###
