"""Add default key validation intervals to config table

Revision ID: e7e214f5785e
Revises: 49ae181f3372
Create Date: 2025-07-01 11:14:23.477889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e214f5785e'
down_revision: Union[str, None] = '49ae181f3372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.Table(
            "config",
            sa.MetaData(),
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("key", sa.String),
            sa.Column("value", sa.Text),
            sa.Column("updated_at", sa.DateTime),
            sa.Column("updated_by_user_id", sa.Integer),
        ),
        [
            {
                "key": "key_validation_active_interval_seconds",
                "value": "600",
                "updated_by_user_id": 1,
            },
            {
                "key": "key_validation_exhausted_interval_seconds",
                "value": "1800",
                "updated_by_user_id": 1,
            },
            {
                "key": "key_validation_error_interval_seconds",
                "value": "86400",
                "updated_by_user_id": 1,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM config WHERE key IN ('key_validation_active_interval_seconds', 'key_validation_exhausted_interval_seconds', 'key_validation_error_interval_seconds')"
    )
    # ### end Alembic commands ###
